# This config file is used by ros2_control
controller_manager:
    ros__parameters:
        update_rate: 100 # Hz

        robotic_arm_controller:
            type: joint_trajectory_controller/JointTrajectoryController

        gripper_controller:
            type: joint_trajectory_controller/JointTrajectoryController

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

robotic_arm_controller:
    ros__parameters:
        joints:
            - joint_1
            - joint_2
            - joint_3
            - joint_4
            - joint_5
            - joint_6
            - joint_7
            - tool_joint
        command_interfaces:
            - position
            - velocity
        state_interfaces:
            - position
            - velocity
        allow_nonzero_velocity_at_trajectory_end: true
gripper_controller:
    ros__parameters:
        joints:
            - grip_left_joint
            - grip_right_joint
        command_interfaces:
            - position
            - velocity
        state_interfaces:
            - position
            - velocity
        allow_nonzero_velocity_at_trajectory_end: true
