use_gazebo: false
publish_period: 0.01 
low_latency_mode: false
auto_start: true
use_twist: true
command_in_type: "unitless"
# command_in_type: "geometry_msgs/TwistStamped"
scale:
  linear:  0.4  
  rotational:  0.8  
  joint: 0.5
command_out_type: trajectory_msgs/JointTrajectory
publish_joint_positions: true
publish_joint_velocities: false
publish_joint_accelerations: false
smoothing_filter_plugin_name: "online_signal_smoothing::ButterworthFilterPlugin"
is_primary_planning_scene_monitor: true
check_octomap_collisions: false 

move_group_name: robotic_arm 
planning_frame: base_link
ee_frame_name: tool_frame
robot_link_command_frame: base_link

lower_singularity_threshold: 17.0  
hard_stop_singularity_threshold: 1000.0
leaving_singularity_threshold_multiplier: 2.0  

joint_limit_margins: [0.12]
cartesian_command_in_topic: ~/delta_twist_cmds 
joint_command_in_topic: ~/delta_joint_cmds
joint_topic: /joint_states 
status_topic: ~/status 
command_out_topic: /robotic_arm_controller/joint_trajectory 

check_collisions: true  
collision_check_rate: 10.0  
self_collision_proximity_threshold: 0.01  
scene_collision_proximity_threshold: 0.02