controller_joint_names:
    [
        "",
        "joint_1",
        "joint_2",
        "joint_3",
        "joint_4",
        "joint_5",
        "joint_6",
        "joint_7",
        "tool_joint",
        "grip_left_joint",
        "grip_right_joint",
    ]
